language: python
python:
  - '3.6'

cache:
  bundler: true
  directories:
    - node_modules

before_install:
  - pip install -U pip
  - pip install vyper==0.1.0b9
  - vyper --version
  - nvm install v10.15.3

install:
  - npm i

script:
  - npm test

dist: trusty
sudo: false
